Updates for BLAST+ 2.15.0
ncbi/docker pull request #39
Opened 2023-11-03 20:46 UTC by christiam

2023-11-03 21:45 UTC, boratyng requested changes

2023-11-03 21:45 UTC, boratyng commented on blast/2.15.0/Dockerfile
> +# cmake installed by apt is currently too old
```suggestion
```

2023-11-03 21:45 UTC, boratyng commented on blast/2.15.0/Dockerfile
> +RUN wget https://github.com/Kitware/CMake/releases/download/v3.22.3/cmake-3.22.3-linux-x86_64.tar.gz && tar xfz cmake-3.22.3-linux-x86_64.tar.gz && rm cmake-3.22.3-linux-x86_64.tar.gz
```suggestion
```
This is not needed if `cmake` is installed with `apt-get`.

2023-11-03 21:45 UTC, boratyng commented on blast/2.15.0/Dockerfile
> +ENV PATH="${PATH}:/root/cmake-3.22.3-linux-x86_64/bin"
```suggestion
```

2023-11-03 21:45 UTC, boratyng commented on blast/2.15.0/Dockerfile
> +RUN apt-get -y -m update && apt-get install -y build-essential curl libidn12 libnet-perl perl-doc liblmdb-dev wget libsqlite3-dev \
```suggestion
RUN apt-get -y -m update && apt-get install -y build-essential curl libidn12 libnet-perl perl-doc liblmdb-dev wget libsqlite3-dev cmake \
```
In ubuntu:22.04 you can use `cmake` installed by `apt-get`.

2023-11-04 01:40 UTC, christiam commented
Thanks for the feedback @boratyng  - I incorporated your suggestions in 250317e

2023-11-09 13:28 UTC, boratyng approved these changes

2023-11-09 14:06 UTC, merged